name: dotnet-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    environment: AZ-Test

    env:
      ApiRootUrl: $API_ROOT_URL 

    steps:
      - uses: actions/checkout@v4

      - name: dependency caching
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: configure test front-end environment
        run: |
            set-content "rubberduckvba.client\src\environments\environment.test.ts" -value "export const environment = { production: false, apiBaseUrl: '$ApiRootUrl' };"
            set-content "rubberduckvba.client\src\environments\environment.prod.ts" -value "export const environment = { production: false, apiBaseUrl: '$ApiRootUrl' };"
            set-content "rubberduckvba.client\src\environments\environment.ts" -value "export const environment = { production: false, apiBaseUrl: '$ApiRootUrl' };"

      - name: dotnet build
        run: dotnet build rubberduckvba.Server --configuration Release

      - name: dotnet publish
        run: dotnet publish "rubberduckvba.Server\rubberduckvba.Server.csproj" --configuration Release --output ${{env.DOTNET_ROOT}}\pub

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pub
          path: ${{env.DOTNET_ROOT}}\pub

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: clear staging
        run: remove-item C:/pub/webroot/test.rubberduckvba.com -Recurse -Force

      - name: download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: pub
          path: C:/pub/pub-test.zip

      - name: staging
        run: move-item C:/pub/pub-test.zip C:/pub/webroot/test.rubberduckvba.com -force
      
      - name: deploy iis site
        run: |
            stop-webapppool -name "DefaultAppPool"
            stop-webapppool -name "rubberduckvba"
            stop-iissite -name api -confirm: $false
            stop-iissite -name rubberduckvba -confirm: $false
            start-sleep -seconds 10
            copy-item C:/pub/webroot/test.rubberduckvba.com/* C:/inetpub/wwwroot/test.rubberduckvba.com -Recurse -Force 
            copy-item C:/inetpub/appsettings.test.json C:/inetpub/wwwroot/test.rubberduckvba.com/appsettings.json -Force
            copy-item C:/inetpub/__Web.config C:/inetpub/wwwroot/test.rubberduckvba.com/wwwroot/browser/Web.config -Force
            start-webapppool rubberduckvba
            start-iissite api
            start-webapppool DefaultAppPool
            start-iissite rubberduckvba
